# -*- coding: utf-8 -*-
"""Metode Desicion Tree

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19LUIGtBBSuPgqlpMZLK7BwHiKFPmAjFT
"""

from sklearn import tree

# Database: Gerbang logika AND
# x = Data, Y = Target
x = [[0,0], [0,1], [1,0], [1,1], [2,0], [2,1], [3,0], [3,1], [1,3], [2,2]]
y = [0,0,0,1,0,0,1,0,0,1]

# Training and Classify
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x,y)

# Prediksi
print ("Logika AND Metode Desicion Tree")
print ("Logika = Prediksi")
print ("0 0 = ", clf.predict([[0,0]]))
print ("0 1 = ", clf.predict([[0,1]]))
print ("1 0 = ", clf.predict([[1,0]]))
print ("1 1 = ", clf.predict([[1,1]]))
print ("2 0 = ", clf.predict([[2,0]]))
print ("2 1 = ", clf.predict([[2,1]]))
print ("3 0 = ", clf.predict([[3,0]]))
print ("3 1 = ", clf.predict([[3,1]]))
print ("1 3 = ", clf.predict([[1,3]]))
print ("2 2 = ", clf.predict([[2,2]]))